# Site settings
title: Language variation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl"

baseurl: "/blog/" 
url: "http://ianbstewart.github.com" # the base hostname & protocol for your site
twitter_username: alethioguy
github_username:  ianbstewart
email: ibs at dartmouth.edu

# Build settings
markdown: kramdown
